name: Security tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ["files", "spam", "user"]

    steps:
    - uses: actions/checkout@v3
    - name: Build Autograder image
      run: |
        cd security_tests
        docker build -t graderimage .
        cd ..
    - name: Run security tests
      run: |
        docker run --rm -v $(pwd)/security_tests/tests/${{ matrix.test }}:/autograder/submission -l sectest graderimage
