# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Security tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["files", "network", "spam", "user"]

    steps:
    - uses: actions/checkout@v3
    - name: Build Autograder image
      run: |
        cd docker_tests
        docker build -t graderimage .
        cd ..
    - name: Run security tests
      run: |
        docker run --rm -v $(pwd)/docker_tests/tests/${{ matrix.test }}:/autograder/submission -l sectest graderimage
